// Auto-generated mappings file
export const providerMappings = {
  "openai": [
    "OPENAI_API_KEY",
    "OPENAI_API_URL",
    "SMALL_OPENAI_MODEL",
    "MEDIUM_OPENAI_MODEL",
    "LARGE_OPENAI_MODEL",
    "EMBEDDING_OPENAI_MODEL",
    "IMAGE_OPENAI_MODEL",
    "USE_OPENAI_EMBEDDING",
    "ENABLE_OPEN_AI_COMMUNITY_PLUGIN",
    "OPENAI_DEFAULT_MODEL",
    "OPENAI_MAX_TOKENS",
    "OPENAI_TEMPERATURE"
  ],
  "atoma": [
    "ATOMASDK_BEARER_AUTH",
    "ATOMA_API_URL",
    "SMALL_ATOMA_MODEL",
    "MEDIUM_ATOMA_MODEL",
    "LARGE_ATOMA_MODEL"
  ],
  "eternalai": [
    "ETERNALAI_URL",
    "ETERNALAI_MODEL",
    "ETERNALAI_CHAIN_ID",
    "ETERNALAI_RPC_URL",
    "ETERNALAI_AGENT_CONTRACT_ADDRESS",
    "ETERNALAI_AGENT_ID",
    "ETERNALAI_API_KEY",
    "ETERNALAI_LOG"
  ],
  "hyperbolic": [
    "HYPERBOLIC_API_KEY",
    "HYPERBOLIC_MODEL",
    "IMAGE_HYPERBOLIC_MODEL",
    "SMALL_HYPERBOLIC_MODEL",
    "MEDIUM_HYPERBOLIC_MODEL",
    "LARGE_HYPERBOLIC_MODEL",
    "HYPERBOLIC_ENV",
    "HYPERBOLIC_GRANULAR_LOG",
    "HYPERBOLIC_SPASH",
    "HYPERBOLIC_LOG_LEVEL"
  ],
  "infera": [
    "INFERA_API_KEY",
    "INFERA_MODEL",
    "INFERA_SERVER_URL",
    "SMALL_INFERA_MODEL",
    "MEDIUM_INFERA_MODEL",
    "LARGE_INFERA_MODEL"
  ],
  "venice": [
    "VENICE_API_KEY",
    "SMALL_VENICE_MODEL",
    "MEDIUM_VENICE_MODEL",
    "LARGE_VENICE_MODEL",
    "IMAGE_VENICE_MODEL"
  ],
  "nineteen_ai": [
    "NINETEEN_AI_API_KEY",
    "SMALL_NINETEEN_AI_MODEL",
    "MEDIUM_NINETEEN_AI_MODEL",
    "LARGE_NINETEEN_AI_MODEL",
    "IMAGE_NINETEEN_AI_MODE"
  ],
  "akash_chat_api": [
    "AKASH_CHAT_API_KEY",
    "SMALL_AKASH_CHAT_API_MODEL",
    "MEDIUM_AKASH_CHAT_API_MODEL",
    "LARGE_AKASH_CHAT_API_MODEL"
  ],
  "livepeer": [
    "LIVEPEER_GATEWAY_URL",
    "IMAGE_LIVEPEER_MODEL",
    "SMALL_LIVEPEER_MODEL",
    "MEDIUM_LIVEPEER_MODEL",
    "LARGE_LIVEPEER_MODEL"
  ],
  "elevenlabs": [
    "ELEVENLABS_XI_API_KEY",
    "ELEVENLABS_MODEL_ID",
    "ELEVENLABS_VOICE_ID",
    "ELEVENLABS_VOICE_STABILITY",
    "ELEVENLABS_VOICE_SIMILARITY_BOOST",
    "ELEVENLABS_VOICE_STYLE",
    "ELEVENLABS_VOICE_USE_SPEAKER_BOOST",
    "ELEVENLABS_OPTIMIZE_STREAMING_LATENCY",
    "ELEVENLABS_OUTPUT_FORMAT"
  ],
  "openrouter": [
    "OPENROUTER_API_KEY",
    "OPENROUTER_MODEL",
    "SMALL_OPENROUTER_MODEL",
    "MEDIUM_OPENROUTER_MODEL",
    "LARGE_OPENROUTER_MODEL"
  ],
  "redpill": [
    "REDPILL_API_KEY",
    "REDPILL_MODEL",
    "SMALL_REDPILL_MODEL",
    "MEDIUM_REDPILL_MODEL",
    "LARGE_REDPILL_MODEL"
  ],
  "grok": [
    "GROK_API_KEY",
    "SMALL_GROK_MODEL",
    "MEDIUM_GROK_MODEL",
    "LARGE_GROK_MODEL",
    "EMBEDDING_GROK_MODEL"
  ],
  "ollama": [
    "OLLAMA_SERVER_URL",
    "OLLAMA_MODEL",
    "USE_OLLAMA_EMBEDDING",
    "OLLAMA_EMBEDDING_MODEL",
    "SMALL_OLLAMA_MODEL",
    "MEDIUM_OLLAMA_MODEL",
    "LARGE_OLLAMA_MODEL"
  ],
  "google": [
    "GOOGLE_MODEL",
    "SMALL_GOOGLE_MODEL",
    "MEDIUM_GOOGLE_MODEL",
    "LARGE_GOOGLE_MODEL",
    "EMBEDDING_GOOGLE_MODEL",
    "GOOGLE_GENERATIVE_AI_API_KEY"
  ],
  "mistral": [
    "MISTRAL_MODEL",
    "SMALL_MISTRAL_MODEL",
    "MEDIUM_MISTRAL_MODEL",
    "LARGE_MISTRAL_MODEL"
  ],
  "groq": [
    "GROQ_API_KEY",
    "SMALL_GROQ_MODEL",
    "MEDIUM_GROQ_MODEL",
    "LARGE_GROQ_MODEL",
    "EMBEDDING_GROQ_MODEL"
  ],
  "llamalocal": [
    "LLAMALOCAL_PATH"
  ],
  "nanogpt": [
    "SMALL_NANOGPT_MODEL",
    "MEDIUM_NANOGPT_MODEL",
    "LARGE_NANOGPT_MODEL",
    "NANOGPT_API_KEY"
  ],
  "anthropic": [
    "ANTHROPIC_API_KEY",
    "SMALL_ANTHROPIC_MODEL",
    "MEDIUM_ANTHROPIC_MODEL",
    "LARGE_ANTHROPIC_MODEL"
  ],
  "heurist": [
    "HEURIST_API_KEY",
    "SMALL_HEURIST_MODEL",
    "MEDIUM_HEURIST_MODEL",
    "LARGE_HEURIST_MODEL",
    "HEURIST_IMAGE_MODEL",
    "HEURIST_EMBEDDING_MODEL",
    "USE_HEURIST_EMBEDDING"
  ],
  "gaianet": [
    "GAIANET_MODEL",
    "GAIANET_SERVER_URL",
    "SMALL_GAIANET_MODEL",
    "SMALL_GAIANET_SERVER_URL",
    "MEDIUM_GAIANET_MODEL",
    "MEDIUM_GAIANET_SERVER_URL",
    "LARGE_GAIANET_MODEL",
    "LARGE_GAIANET_SERVER_URL",
    "GAIANET_EMBEDDING_MODEL",
    "USE_GAIANET_EMBEDDING"
  ],
  "volengine": [
    "VOLENGINE_API_URL",
    "VOLENGINE_MODEL",
    "SMALL_VOLENGINE_MODEL",
    "MEDIUM_VOLENGINE_MODEL",
    "LARGE_VOLENGINE_MODEL",
    "VOLENGINE_EMBEDDING_MODEL"
  ],
  "deepseek": [
    "DEEPSEEK_API_KEY",
    "DEEPSEEK_API_URL",
    "SMALL_DEEPSEEK_MODEL",
    "MEDIUM_DEEPSEEK_MODEL",
    "LARGE_DEEPSEEK_MODEL"
  ],
  "falai": [
    "FAL_API_KEY",
    "FAL_AI_LORA_PATH"
  ],
  "letzai": [
    "LETZAI_API_KEY",
    "LETZAI_MODELS"
  ],
  "galadriel": [
    "GALADRIEL_API_KEY",
    "SMALL_GALADRIEL_MODEL",
    "MEDIUM_GALADRIEL_MODEL",
    "LARGE_GALADRIEL_MODEL",
    "GALADRIEL_FINE_TUNE_API_KEY"
  ],
  "lmstudio": [
    "LMSTUDIO_SERVER_URL",
    "LMSTUDIO_MODEL",
    "SMALL_LMSTUDIO_MODEL",
    "MEDIUM_LMSTUDIO_MODEL",
    "LARGE_LMSTUDIO_MODEL"
  ],
  "secret_ai": [
    "SECRET_AI_API_KEY",
    "SECRET_AI_URL",
    "SMALL_SECRET_AI_MODEL",
    "MEDIUM_SECRET_AI_MODEL",
    "LARGE_SECRET_AI_MODEL"
  ],
  "nearai": [
    "NEARAI_API_URL",
    "NEARAI_API_KEY",
    "NEARAI_MODEL",
    "SMALL_NEARAI_MODEL",
    "MEDIUM_NEARAI_MODEL",
    "LARGE_NEARAI_MODEL",
    "IMAGE_NEARAI_MODEL"
  ],
  "together": [
    "TOGETHER_API_KEY"
  ],
  "ali_bailian": [
    "ALI_BAILIAN_API_KEY"
  ]
} as const;

export const clientMappings = {
  "discord": [
    "DISCORD_APPLICATION_ID",
    "DISCORD_API_TOKEN",
    "DISCORD_VOICE_CHANNEL_ID"
  ],
  "farcaster": [
    "FARCASTER_FID",
    "FARCASTER_NEYNAR_API_KEY",
    "FARCASTER_NEYNAR_SIGNER_UUID",
    "FARCASTER_DRY_RUN",
    "FARCASTER_POLL_INTERVAL"
  ],
  "telegram": [
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_ACCOUNT_PHONE",
    "TELEGRAM_ACCOUNT_APP_ID",
    "TELEGRAM_ACCOUNT_APP_HASH",
    "TELEGRAM_ACCOUNT_DEVICE_MODEL",
    "TELEGRAM_ACCOUNT_SYSTEM_VERSION"
  ],
  "twitter": [
    "TWITTER_DRY_RUN",
    "TWITTER_USERNAME",
    "TWITTER_PASSWORD",
    "TWITTER_EMAIL",
    "TWITTER_2FA_SECRET",
    "TWITTER_COOKIES_AUTH_TOKEN",
    "TWITTER_COOKIES_CT0",
    "TWITTER_COOKIES_GUEST_ID",
    "TWITTER_POLL_INTERVAL",
    "TWITTER_SEARCH_ENABLE",
    "TWITTER_TARGET_USERS",
    "TWITTER_RETRY_LIMIT",
    "TWITTER_SPACES_ENABLE",
    "ENABLE_TWITTER_POST_GENERATION",
    "POST_INTERVAL_MIN",
    "POST_INTERVAL_MAX",
    "POST_IMMEDIATELY",
    "ACTION_INTERVAL",
    "ENABLE_ACTION_PROCESSING",
    "MAX_ACTIONS_PROCESSING",
    "ACTION_TIMELINE_TYPE",
    "TWITTER_APPROVAL_DISCORD_CHANNEL_ID",
    "TWITTER_APPROVAL_DISCORD_BOT_TOKEN",
    "TWITTER_APPROVAL_ENABLED",
    "TWITTER_APPROVAL_CHECK_INTERVAL"
  ],
  "whatsapp": [
    "WHATSAPP_ACCESS_TOKEN",
    "WHATSAPP_PHONE_NUMBER_ID",
    "WHATSAPP_BUSINESS_ACCOUNT_ID",
    "WHATSAPP_WEBHOOK_VERIFY_TOKEN",
    "WHATSAPP_API_VERSION"
  ],
  "instagram": [
    "INSTAGRAM_DRY_RUN",
    "INSTAGRAM_USERNAME",
    "INSTAGRAM_PASSWORD",
    "INSTAGRAM_APP_ID",
    "INSTAGRAM_APP_SECRET",
    "INSTAGRAM_BUSINESS_ACCOUNT_ID",
    "INSTAGRAM_POST_INTERVAL_MIN",
    "INSTAGRAM_POST_INTERVAL_MAX",
    "INSTAGRAM_ENABLE_ACTION_PROCESSING",
    "INSTAGRAM_ACTION_INTERVAL",
    "INSTAGRAM_MAX_ACTIONS"
  ],
  "alexa": [
    "ALEXA_SKILL_ID",
    "ALEXA_CLIENT_ID",
    "ALEXA_CLIENT_SECRET"
  ],
  "simsai": [
    "SIMSAI_API_KEY",
    "SIMSAI_AGENT_ID",
    "SIMSAI_USERNAME",
    "SIMSAI_DRY_RUN"
  ]
} as const;

export const pluginMappings = {
  "coinmarketcap": [
    "COINMARKETCAP_API_KEY"
  ],
  "zerion": [
    "ZERION_API_KEY"
  ],
  "coingecko": [
    "COINGECKO_API_KEY",
    "COINGECKO_PRO_API_KEY"
  ],
  "moralis": [
    "MORALIS_API_KEY"
  ],
  "evm": [
    "EVM_PRIVATE_KEY",
    "EVM_PROVIDER_URL"
  ],
  "zilliqa": [
    "ZILLIQA_PRIVATE_KEY",
    "ZILLIQA_PROVIDER_URL"
  ],
  "avalanche": [
    "AVALANCHE_PRIVATE_KEY",
    "AVALANCHE_PUBLIC_KEY"
  ],
  "arthera": [
    "ARTHERA_PRIVATE_KEY"
  ],
  "solana": [
    "SOLANA_PRIVATE_KEY",
    "SOLANA_PUBLIC_KEY",
    "SOLANA_CLUSTER",
    "SOLANA_ADMIN_PRIVATE_KEY",
    "SOLANA_ADMIN_PUBLIC_KEY",
    "SOLANA_VERIFY_TOKEN",
    "SOL_ADDRESS",
    "SLIPPAGE",
    "BASE_MINT",
    "SOLANA_RPC_URL",
    "HELIUS_API_KEY"
  ],
  "injective": [
    "INJECTIVE_PRIVATE_KEY",
    "INJECTIVE_PUBLIC_KEY",
    "INJECTIVE_NETWORK"
  ],
  "birdeye": [
    "BIRDEYE_API_KEY"
  ],
  "abstract": [
    "ABSTRACT_ADDRESS",
    "ABSTRACT_PRIVATE_KEY",
    "ABSTRACT_RPC_URL"
  ],
  "starknet": [
    "STARKNET_ADDRESS",
    "STARKNET_PRIVATE_KEY",
    "STARKNET_RPC_URL"
  ],
  "lens": [
    "LENS_ADDRESS",
    "LENS_PRIVATE_KEY"
  ],
  "form": [
    "FORM_PRIVATE_KEY",
    "FORM_TESTNET"
  ],
  "coinbase": [
    "COINBASE_COMMERCE_KEY",
    "COINBASE_API_KEY",
    "COINBASE_PRIVATE_KEY",
    "COINBASE_GENERATED_WALLET_ID",
    "COINBASE_GENERATED_WALLET_HEX_SEED",
    "COINBASE_NOTIFICATION_URI"
  ],
  "coinbase_agentkit": [
    "CDP_API_KEY_NAME",
    "CDP_API_KEY_PRIVATE_KEY",
    "CDP_AGENT_KIT_NETWORK"
  ],
  "coinbase_charity": [
    "IS_CHARITABLE",
    "CHARITY_ADDRESS_BASE",
    "CHARITY_ADDRESS_SOL",
    "CHARITY_ADDRESS_ETH",
    "CHARITY_ADDRESS_ARB",
    "CHARITY_ADDRESS_POL"
  ],
  "thirdweb": [
    "THIRDWEB_SECRET_KEY"
  ],
  "conflux": [
    "CONFLUX_CORE_PRIVATE_KEY",
    "CONFLUX_CORE_SPACE_RPC_URL",
    "CONFLUX_ESPACE_PRIVATE_KEY",
    "CONFLUX_ESPACE_RPC_URL",
    "CONFLUX_MEME_CONTRACT_ADDRESS"
  ],
  "mind_network": [
    "MIND_HOT_WALLET_PRIVATE_KEY",
    "MIND_COLD_WALLET_ADDRESS"
  ],
  "0g": [
    "ZEROG_INDEXER_RPC",
    "ZEROG_EVM_RPC",
    "ZEROG_PRIVATE_KEY",
    "ZEROG_FLOW_ADDRESS"
  ],
  "iq6900": [
    "IQ_WALLET_ADDRESS",
    "IQSOlRPC"
  ],
  "squid_router": [
    "SQUID_SDK_URL",
    "SQUID_INTEGRATOR_ID",
    "SQUID_EVM_ADDRESS",
    "SQUID_EVM_PRIVATE_KEY",
    "SQUID_API_THROTTLE_INTERVAL"
  ],
  "tee": [
    "TEE_MODE",
    "WALLET_SECRET_SALT",
    "TEE_LOG_DB_PATH",
    "VLOG",
    "ENABLE_TEE_LOG"
  ],
  "flow": [
    "FLOW_ADDRESS",
    "FLOW_PRIVATE_KEY",
    "FLOW_NETWORK",
    "FLOW_ENDPOINT_URL"
  ],
  "icp": [
    "INTERNET_COMPUTER_PRIVATE_KEY",
    "INTERNET_COMPUTER_ADDRESS"
  ],
  "aptos": [
    "APTOS_PRIVATE_KEY",
    "APTOS_NETWORK"
  ],
  "multiversx": [
    "MVX_PRIVATE_KEY",
    "MVX_NETWORK",
    "ACCESS_TOKEN_MANAGEMENT_TO"
  ],
  "near": [
    "NEAR_WALLET_SECRET_KEY",
    "NEAR_WALLET_PUBLIC_KEY",
    "NEAR_ADDRESS",
    "NEAR_SLIPPAGE",
    "NEAR_RPC_URL",
    "NEAR_NETWORK"
  ],
  "zksync": [
    "ZKSYNC_ADDRESS",
    "ZKSYNC_PRIVATE_KEY"
  ],
  "holdstation": [
    "HOLDSTATION_PRIVATE_KEY"
  ],
  "avail": [
    "AVAIL_ADDRESS",
    "AVAIL_SEED",
    "AVAIL_APP_ID",
    "AVAIL_RPC_URL"
  ],
  "tee_marlin": [
    "TEE_MARLIN",
    "TEE_MARLIN_ATTESTATION_ENDPOINT"
  ],
  "ton": [
    "TON_PRIVATE_KEY",
    "TON_RPC_URL",
    "TON_RPC_API_KEY",
    "TON_NFT_IMAGES_FOLDER",
    "TON_NFT_METADATA_FOLDER",
    "PINATA_API_KEY",
    "PINATA_API_SECRET"
  ],
  "sui": [
    "SUI_PRIVATE_KEY",
    "SUI_NETWORK"
  ],
  "mina": [
    "MINA_PRIVATE_KEY",
    "MINA_NETWORK"
  ],
  "story": [
    "STORY_PRIVATE_KEY",
    "STORY_API_BASE_URL",
    "STORY_API_KEY",
    "PINATA_JWT"
  ],
  "cosmos": [
    "COSMOS_RECOVERY_PHRASE",
    "COSMOS_AVAILABLE_CHAINS"
  ],
  "cronoszkevm": [
    "CRONOSZKEVM_ADDRESS",
    "CRONOSZKEVM_PRIVATE_KEY"
  ],
  "fuel": [
    "FUEL_WALLET_PRIVATE_KEY"
  ],
  "spheron": [
    "SPHERON_PRIVATE_KEY",
    "SPHERON_PROVIDER_PROXY_URL",
    "SPHERON_WALLET_ADDRESS"
  ],
  "stargaze": [
    "STARGAZE_ENDPOINT"
  ],
  "genlayer": [
    "GENLAYER_PRIVATE_KEY"
  ],
  "gelato": [
    "GELATO_RELAY_API_KEY"
  ],
  "bnb": [
    "BNB_PRIVATE_KEY",
    "BNB_PUBLIC_KEY",
    "BSC_PROVIDER_URL",
    "OPBNB_PROVIDER_URL"
  ],
  "web_search": [
    "TAVILY_API_KEY"
  ],
  "bitmind": [
    "BITMIND",
    "BITMIND_API_TOKEN"
  ],
  "devin": [
    "DEVIN_API_TOKEN"
  ],
  "intiface": [
    "INTIFACE_WEBSOCKET_URL"
  ],
  "giphy": [
    "GIPHY_API_KEY"
  ],
  "openweather": [
    "OPEN_WEATHER_API_KEY"
  ],
  "gitcoin_passport": [
    "PASSPORT_API_KEY",
    "PASSPORT_SCORER"
  ],
  "echochambers": [
    "ECHOCHAMBERS_API_URL",
    "ECHOCHAMBERS_API_KEY",
    "ECHOCHAMBERS_USERNAME",
    "ECHOCHAMBERS_ROOMS",
    "ECHOCHAMBERS_POLL_INTERVAL",
    "ECHOCHAMBERS_MAX_MESSAGES",
    "ECHOCHAMBERS_CONVERSATION_STARTER_INTERVAL",
    "ECHOCHAMBERS_QUIET_PERIOD"
  ],
  "allora": [
    "ALLORA_API_KEY",
    "ALLORA_CHAIN_SLUG"
  ],
  "b2": [
    "B2_PRIVATE_KEY"
  ],
  "opacity": [
    "OPACITY_TEAM_ID",
    "OPACITY_CLOUDFLARE_NAME",
    "OPACITY_PROVER_URL"
  ],
  "deva": [
    "DEVA_API_KEY",
    "DEVA_API_BASE_URL"
  ],
  "deepgram": [
    "DEEPGRAM_API_KEY"
  ],
  "qdrant": [
    "QDRANT_URL",
    "QDRANT_KEY",
    "QDRANT_PORT",
    "QDRANT_VECTOR_SIZE"
  ],
  "autonome": [
    "AUTONOME_JWT_TOKEN",
    "AUTONOME_RPC"
  ],
  "akash": [
    "AKASH_ENV",
    "AKASH_NET",
    "RPC_ENDPOINT",
    "AKASH_GAS_PRICES",
    "AKASH_GAS_ADJUSTMENT",
    "AKASH_KEYRING_BACKEND",
    "AKASH_FROM",
    "AKASH_FEES",
    "AKASH_DEPOSIT",
    "AKASH_MNEMONIC",
    "AKASH_WALLET_ADDRESS",
    "AKASH_PRICING_API_URL",
    "AKASH_DEFAULT_CPU",
    "AKASH_DEFAULT_MEMORY",
    "AKASH_DEFAULT_STORAGE",
    "AKASH_SDL",
    "AKASH_CLOSE_DEP",
    "AKASH_CLOSE_DSEQ",
    "AKASH_PROVIDER_INFO",
    "AKASH_DEP_STATUS",
    "AKASH_DEP_DSEQ",
    "AKASH_GAS_OPERATION",
    "AKASH_GAS_DSEQ",
    "AKASH_MANIFEST_MODE",
    "AKASH_MANIFEST_PATH",
    "AKASH_MANIFEST_VALIDATION_LEVEL"
  ],
  "quai": [
    "QUAI_PRIVATE_KEY",
    "QUAI_RPC_URL"
  ],
  "chainbase": [
    "CHAINBASE_API_KEY"
  ],
  "0x": [
    "ZERO_EX_API_KEY",
    "ALCHEMY_HTTP_TRANSPORT_URL"
  ],
  "pyth_data": [
    "PYTH_NETWORK_ENV",
    "PYTH_MAINNET_HERMES_URL",
    "PYTH_MAINNET_WSS_URL",
    "PYTH_MAINNET_PYTHNET_URL",
    "PYTH_MAINNET_CONTRACT_REGISTRY",
    "PYTH_MAINNET_PROGRAM_KEY",
    "PYTH_TESTNET_HERMES_URL",
    "PYTH_TESTNET_WSS_URL",
    "PYTH_TESTNET_PYTHNET_URL",
    "PYTH_TESTNET_CONTRACT_REGISTRY",
    "PYTH_TESTNET_PROGRAM_KEY",
    "PYTH_MAX_RETRIES",
    "PYTH_RETRY_DELAY",
    "PYTH_TIMEOUT",
    "PYTH_GRANULAR_LOG",
    "PYTH_LOG_LEVEL",
    "RUNTIME_CHECK_MODE",
    "PYTH_ENABLE_PRICE_STREAMING",
    "PYTH_MAX_PRICE_STREAMS",
    "PYTH_TEST_ID01",
    "PYTH_TEST_ID02"
  ],
  "router_nitro": [
    "ROUTER_NITRO_EVM_ADDRESS",
    "ROUTER_NITRO_EVM_PRIVATE_KEY"
  ],
  "dkg": [
    "DKG_ENVIRONMENT",
    "DKG_HOSTNAME",
    "DKG_PORT",
    "DKG_PUBLIC_KEY",
    "DKG_PRIVATE_KEY",
    "DKG_BLOCKCHAIN_NAME"
  ],
  "initia": [
    "INITIA_PRIVATE_KEY",
    "INITIA_NODE_URL",
    "INITIA_CHAIN_ID"
  ],
  "nvidia_nim": [
    "NVIDIA_NIM_ENV",
    "NVIDIA_NIM_SPASH",
    "NVIDIA_NIM_API_KEY",
    "NVIDIA_NGC_API_KEY",
    "NVIDIA_NIM_MAX_RETRIES",
    "NVIDIA_NIM_RETRY_DELAY",
    "NVIDIA_NIM_TIMEOUT",
    "NVIDIA_GRANULAR_LOG",
    "NVIDIA_LOG_LEVEL",
    "NVIDIA_OFFTOPIC_SYSTEM",
    "NVIDIA_OFFTOPIC_USER",
    "NVIDIA_NIM_BASE_VISION_URL",
    "NVIDIA_COSMOS_MODEL",
    "NVIDIA_COSMOS_INVOKE_URL",
    "NVIDIA_COSMOS_ASSET_URL",
    "NVIDIA_COSMOS_MAX_TOKENS"
  ],
  "email": [
    "EMAIL_OUTGOING_SERVICE",
    "EMAIL_OUTGOING_HOST",
    "EMAIL_OUTGOING_PORT",
    "EMAIL_OUTGOING_USER",
    "EMAIL_OUTGOING_PASS",
    "EMAIL_INCOMING_SERVICE",
    "EMAIL_INCOMING_HOST",
    "EMAIL_INCOMING_PORT",
    "EMAIL_INCOMING_USER",
    "EMAIL_INCOMING_PASS"
  ],
  "sei": [
    "SEI_PRIVATE_KEY",
    "SEI_NETWORK",
    "SEI_RPC_URL"
  ],
  "omniflix": [
    "OMNIFLIX_API_URL",
    "OMNIFLIX_MNEMONIC",
    "OMNIFLIX_RPC_ENDPOINT",
    "OMNIFLIX_PRIVATE_KEY"
  ],
  "suno": [
    "SUNO_API_KEY"
  ],
  "udio": [
    "UDIO_AUTH_TOKEN"
  ],
  "football": [
    "FOOTBALL_API_KEY"
  ],
  "imgflip": [
    "IMGFLIP_USERNAME",
    "IMGFLIP_PASSWORD"
  ],
  "hyperliquid": [
    "HYPERLIQUID_PRIVATE_KEY",
    "HYPERLIQUID_TESTNET"
  ],
  "lit": [
    "FUNDING_PRIVATE_KEY",
    "EVM_RPC_URL"
  ],
  "ethstorage": [
    "ETHSTORAGE_PRIVATE_KEY",
    "ETHSTORAGE_ADDRESS",
    "ETHSTORAGE_RPC_URL"
  ],
  "email_automation": [
    "RESEND_API_KEY",
    "DEFAULT_TO_EMAIL",
    "DEFAULT_FROM_EMAIL",
    "EMAIL_AUTOMATION_ENABLED",
    "EMAIL_EVALUATION_PROMPT"
  ],
  "ankr": [
    "ANKR_ENV",
    "ANKR_WALLET",
    "ANKR_MAX_RETRIES",
    "ANKR_RETRY_DELAY",
    "ANKR_TIMEOUT",
    "ANKR_GRANULAR_LOG",
    "ANKR_LOG_LEVEL",
    "ANKR_RUNTIME_CHECK_MODE",
    "ANKR_SPASH"
  ],
  "dcap": [
    "DCAP_EVM_PRIVATE_KEY",
    "DCAP_MODE"
  ],
  "quick_intel": [
    "QUICKINTEL_API_KEY"
  ],
  "news": [
    "NEWS_API_KEY"
  ],
  "btcfun": [
    "BTCFUN_API_URL",
    "BTC_PRIVATE_KEY_WIF",
    "BTC_ADDRESS",
    "BTC_MINT_CAP",
    "BTC_MINT_DEADLINE",
    "BTC_FUNDRAISING_CAP"
  ],
  "trikon": [
    "TRIKON_WALLET_ADDRESS",
    "TRIKON_INITIAL_BALANCE"
  ],
  "arbitrage": [
    "ARBITRAGE_ETHEREUM_WS_URL",
    "ARBITRAGE_EVM_PROVIDER_URL",
    "ARBITRAGE_EVM_PRIVATE_KEY",
    "FLASHBOTS_RELAY_SIGNING_KEY",
    "BUNDLE_EXECUTOR_ADDRESS"
  ],
  "desk_exchange": [
    "DESK_EXCHANGE_PRIVATE_KEY",
    "DESK_EXCHANGE_NETWORK"
  ],
  "compass": [
    "COMPASS_WALLET_PRIVATE_KEY",
    "COMPASS_ARBITRUM_RPC_URL",
    "COMPASS_ETHEREUM_RPC_URL",
    "COMPASS_BASE_RPC_URL"
  ],
  "nkn": [
    "NKN_CLIENT_PRIVATE_KEY",
    "NKN_CLIENT_ID"
  ]
} as const;
